server:
  port: 8092

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost

spring:
  application:
    name: PET-SERVICE


swagger:
  productionURL: https://patientsettings.cmd.skillassure.com/patientsettings

rest:
  appointmentService: http://APPOINTMENT-SERVICE/
  settingService: http://SETTING-SERVICE



