server:
  port: 8093

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://service.cmd.skillassure.com/service

  instance:
    hostname: service.cmd.skillassure.com

spring:
  application:
    name: SETTING-SERVICE

  datasource:
    url: jdbc:mysql://petzey-opteamix.mysql.database.azure.com:3306/SettingService?createDatabaseIfNotExist=true
    username: petzey
    password: Login@123

  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

swagger:
  productionURL: https://setting.cmd.skillassure.com/setting

rest:
  appointmentService: http://APPOINTMENT-SERVICE/



